# -*- coding: utf-8 -*-
"""Emotional Wellness Companion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16S04PamFzcbm8ZXy1_o8aDD1ZnJSxHFs
"""

# STEP 1: Install libraries
!pip install gradio transformers --quiet

# STEP 2: Import and load the model
from transformers import pipeline
import gradio as gr

# Load a more comprehensive emotion classifier (28 emotions)
emotion_classifier = pipeline(
    "text-classification",
    model="SamLowe/roberta-base-go_emotions",
    return_all_scores=True
)

# STEP 3: Expanded dictionary of tips, quotes, and links
tips_and_quotes = {
    "admiration": {
        "tip": "Channel admiration into inspiration for your own growth.",
        "quote": "“Admiration is a very short-lived passion that immediately decays upon growing familiar with its object.” – Joseph Addison",
        "link": "https://www.psychologytoday.com/us/blog/stronger-the-broken-places/202108/the-psychology-admiration"
    },
    "amusement": {
        "tip": "Share what amuses you with others to spread joy.",
        "quote": "“A day without laughter is a day wasted.” – Charlie Chaplin",
        "link": "https://www.helpguide.org/articles/mental-health/laughter-is-the-best-medicine.htm"
    },
    "anger": {
        "tip": "Practice deep breathing or count to ten before reacting.",
        "quote": "“Speak when you are angry and you will make the best speech you will ever regret.” – Ambrose Bierce",
        "link": "https://www.apa.org/topics/anger/control"
    },
    "annoyance": {
        "tip": "Identify the source and consider if it's worth your energy.",
        "quote": "“Rule #1: Don't sweat the small stuff. Rule #2: It's all small stuff.” – Robert Eliot",
        "link": "https://www.psychologytoday.com/us/blog/click-here-happiness/202105/how-stop-getting-annoyed-little-things"
    },
    "approval": {
        "tip": "Give approval to others as freely as you'd like to receive it.",
        "quote": "“Appreciation can make a day, even change a life.” – Margaret Cousins",
        "link": "https://positivepsychology.com/gratitude-appreciation/"
    },
    "caring": {
        "tip": "Practice self-care so you can care for others without burnout.",
        "quote": "“Too often we underestimate the power of a touch, a smile, a kind word, a listening ear.” – Leo Buscaglia",
        "link": "https://www.helpguide.org/articles/relationships-communication/caring-for-your-mental-health.htm"
    },
    "confusion": {
        "tip": "Break problems into smaller parts and tackle them one at a time.",
        "quote": "“Confusion is the welcome mat at the door of creativity.” – Michael J. Gelb",
        "link": "https://www.psychologytoday.com/us/blog/seeing-what-others-dont/201308/the-surprising-benefits-confusion"
    },
    "curiosity": {
        "tip": "Follow your curiosity - it often leads to growth and discovery.",
        "quote": "“The important thing is not to stop questioning. Curiosity has its own reason for existing.” – Albert Einstein",
        "link": "https://greatergood.berkeley.edu/article/item/how_curiosity_makes_your_brain_happy"
    },
    "desire": {
        "tip": "Examine your desires to understand what truly matters to you.",
        "quote": "“Desire is the starting point of all achievement.” – Napoleon Hill",
        "link": "https://www.psychologytoday.com/us/blog/fulfillment-any-age/201109/the-psychology-desire"
    },
    "disappointment": {
        "tip": "See disappointments as redirections rather than rejections.",
        "quote": "“Disappointment is just the action of your brain readjusting itself to reality after discovering things are not the way you thought they were.” – Brad Warner",
        "link": "https://www.psychologytoday.com/us/blog/the-squeaky-wheel/201307/7-ways-get-over-big-disappointment"
    },
    "disapproval": {
        "tip": "Express disapproval constructively with suggestions for improvement.",
        "quote": "“Criticism, like rain, should be gentle enough to nourish a man's growth without destroying his roots.” – Frank A. Clark",
        "link": "https://hbr.org/2019/11/the-art-of-giving-and-receiving-advice"
    },
    "disgust": {
        "tip": "Understand what triggers your disgust to better manage reactions.",
        "quote": "“Disgust is the guardian of the temple of the body.” – William Heberden",
        "link": "https://www.psychologytoday.com/us/blog/hide-and-seek/201601/the-six-basic-emotions-disgust"
    },
    "embarrassment": {
        "tip": "Remember that most people are focused on themselves, not your mistakes.",
        "quote": "“You wouldn't worry so much about what others think of you if you realized how seldom they do.” – Eleanor Roosevelt",
        "link": "https://www.psychologytoday.com/us/blog/fulfillment-any-age/201303/why-am-i-so-easily-embarrassed"
    },
    "excitement": {
        "tip": "Channel excitement into productive energy and creative projects.",
        "quote": "“Excitement is the electricity of life. How do you get it? You act excited until you make it a habit.” – Gordon Parks",
        "link": "https://www.psychologytoday.com/us/blog/the-athletes-way/201308/why-excitement-may-be-more-important-happiness"
    },
    "fear": {
        "tip": "Face fears gradually through exposure and positive self-talk.",
        "quote": "“The only thing we have to fear is fear itself.” – Franklin D. Roosevelt",
        "link": "https://www.helpguide.org/articles/anxiety/facing-your-fears.htm"
    },
    "gratitude": {
        "tip": "Keep a gratitude journal to regularly acknowledge what you appreciate.",
        "quote": "“Gratitude turns what we have into enough.” – Aesop",
        "link": "https://positivepsychology.com/gratitude-appreciation/"
    },
    "grief": {
        "tip": "Allow yourself to feel grief fully - it's part of the healing process.",
        "quote": "“Grief is the price we pay for love.” – Queen Elizabeth II",
        "link": "https://www.helpguide.org/articles/grief/coping-with-grief-and-loss.htm"
    },
    "joy": {
        "tip": "Savor joyful moments by being fully present in them.",
        "quote": "“Joy is the simplest form of gratitude.” – Karl Barth",
        "link": "https://greatergood.berkeley.edu/topic/joy"
    },
    "love": {
        "tip": "Express love regularly through words and actions.",
        "quote": "“Where there is love there is life.” – Mahatma Gandhi",
        "link": "https://www.psychologytoday.com/us/basics/love"
    },
    "nervousness": {
        "tip": "Convert nervous energy into preparation and practice.",
        "quote": "“Nervousness is the energy you don't know how to use.” – Harvey Mackay",
        "link": "https://www.helpguide.org/articles/anxiety/how-to-stop-worrying.htm"
    },
    "optimism": {
        "tip": "Cultivate optimism by focusing on solutions rather than problems.",
        "quote": "“Optimism is the faith that leads to achievement.” – Helen Keller",
        "link": "https://positivepsychology.com/optimism/"
    },
    "pride": {
        "tip": "Take pride in your efforts as much as your accomplishments.",
        "quote": "“Pride helps us; and pride is not a bad thing when it only urges us to hide our own hurts—not to hurt others.” – George Eliot",
        "link": "https://positivepsychology.com/positive-pride/"
    },
    "realization": {
        "tip": "Act on realizations while they're fresh in your mind.",
        "quote": "“Realizations are like sunrises - they come when they're ready, not when you're ready.” – Rasheed Ogunlaru",
        "link": "https://www.psychologytoday.com/us/blog/click-here-happiness/201809/how-have-more-epiphanies"
    },
    "relief": {
        "tip": "Use moments of relief to reset and recharge.",
        "quote": "“To feel the relief of letting go is a gift in itself.” – Anonymous",
        "link": "https://www.psychologytoday.com/us/blog/emotional-nourishment/201809/the-psychology-relief"
    },
    "remorse": {
        "tip": "Make amends where possible, then focus on doing better.",
        "quote": "“Remorse is the poison of life.” – Charlotte Brontë",
        "link": "https://www.psychologytoday.com/us/blog/tech-happy-life/201809/how-deal-regret"
    },
    "sadness": {
        "tip": "Allow yourself to feel sadness without judgment - it's a natural emotion.",
        "quote": "“There is no point treating a depressed person as though she were just feeling sad, saying, 'There now, hang on, you'll get over it.'” – J.K. Rowling",
        "link": "https://www.helpguide.org/articles/depression/coping-with-depression.htm"
    },
    "surprise": {
        "tip": "Embrace surprises as opportunities for new experiences.",
        "quote": "“Life is full of surprises and serendipity.” – Condoleezza Rice",
        "link": "https://www.psychologytoday.com/us/blog/the-science-success/201108/how-embrace-the-unexpected"
    },
    "neutral": {
        "tip": "Use neutral moments for reflection and planning.",
        "quote": "“In the midst of movement and chaos, keep stillness inside of you.” – Deepak Chopra",
        "link": "https://www.mindful.org/how-to-practice-mindfulness/"
    }
}

# STEP 4: Enhanced chatbot logic with error handling
def wellness_bot(message):
    try:
        if not message.strip():
            return "Please share how you're feeling to get personalized support."

        results = emotion_classifier(message)
        top_emotion = sorted(results[0], key=lambda x: x['score'], reverse=True)[0]['label'].lower()

        # Get data for detected emotion or use default if not found
        data = tips_and_quotes.get(top_emotion, {
            "tip": "Practice mindfulness to stay present with your emotions.",
            "quote": "“This too shall pass.” – Persian proverb",
            "link": "https://www.helpguide.org/articles/mental-health/building-better-mental-health.htm"
        })

        response = f"""**Emotion detected:** {top_emotion.capitalize()}\n\n"""
        response += f"""🧠 **Tip:** {data['tip']}\n\n"""
        response += f"""💬 **Quote:** {data['quote']}\n\n"""
        response += f"""📚 **Learn more:** [Click here]({data['link']})"""

        return response

    except Exception as e:
        return f"⚠️ Sorry, I encountered an error. Please try again or rephrase your message.\n\n(Technical details: {str(e)})"

# STEP 5: Launch the enhanced interface
gr.Interface(
    fn=wellness_bot,
    inputs=gr.Textbox(lines=3, placeholder="How are you feeling today? Share your thoughts or emotions..."),
    outputs=gr.Markdown(),
    title="🧠 Emotional Wellness Companion",
    description="""Share how you're feeling and receive personalized emotional support,
    coping tips, and inspirational quotes. This AI recognizes 28 different emotions!""",
    examples=[
        ["I'm feeling really anxious about my upcoming exam"],
        ["Just got promoted at work and I'm thrilled!"],
        ["Feeling lonely after moving to a new city"],
        ["Mixed emotions about my relationship right now"]
    ],
    allow_flagging="never",
    theme="soft"
).launch(share=True)